name: Build ndstool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build ndstool
      run: cmake --build build

    - name: Check build output
      run: |
        if [ -f build/ndstool ]; then
          echo "ndstool built successfully"
          ./build/ndstool --version || echo "No version info"
        else
          echo "Build failed: ndstool executable missing"
          exit 1
        fi
